# Autogenerated wrapper script for LAME_jll for i686-w64-mingw32
export lame, libmp3lame

## Global variables
PATH = ""
LIBPATH = ""
LIBPATH_env = "PATH"

# Relative path to `lame`
const lame_splitpath = ["bin", "lame.exe"]

# This will be filled out by __init__() for all products, as it must be done at runtime
lame_path = ""

# lame-specific global declaration
function lame(f::Function; adjust_PATH::Bool = true, adjust_LIBPATH::Bool = true)
    global PATH, LIBPATH
    env_mapping = Dict{String,String}()
    if adjust_PATH
        if !isempty(get(ENV, "PATH", ""))
            env_mapping["PATH"] = string(PATH, ';', ENV["PATH"])
        else
            env_mapping["PATH"] = PATH
        end
    end
    if adjust_LIBPATH
        if !isempty(get(ENV, LIBPATH_env, ""))
            env_mapping[LIBPATH_env] = string(LIBPATH, ';', ENV[LIBPATH_env])
        else
            env_mapping[LIBPATH_env] = LIBPATH
        end
    end
    withenv(env_mapping...) do
        f(lame_path)
    end
end


# Relative path to `libmp3lame`
const libmp3lame_splitpath = ["bin", "libmp3lame-0.dll"]

# This will be filled out by __init__() for all products, as it must be done at runtime
libmp3lame_path = ""

# libmp3lame-specific global declaration
# This will be filled out by __init__()
libmp3lame_handle = C_NULL

# This must be `const` so that we can use it with `ccall()`
const libmp3lame = "libmp3lame-0.dll"


"""
Open all libraries
"""
function __init__()
    global prefix = abspath(joinpath(@__DIR__, ".."))

    # Initialize PATH and LIBPATH environment variable listings
    global PATH_list, LIBPATH_list
    global lame_path = abspath(joinpath(artifact"LAME", lame_splitpath...))

    push!(PATH_list, dirname(lame_path))
    global libmp3lame_path = abspath(joinpath(artifact"LAME", libmp3lame_splitpath...))

    # Manually `dlopen()` this right now so that future invocations
    # of `ccall` with its `SONAME` will find this path immediately.
    global libmp3lame_handle = dlopen(libmp3lame_path)
    push!(LIBPATH_list, dirname(libmp3lame_path))

    # Filter out duplicate and empty entries in our PATH and LIBPATH entries
    filter!(!isempty, unique!(PATH_list))
    filter!(!isempty, unique!(LIBPATH_list))
    global PATH = join(PATH_list, ';')
    global LIBPATH = join(LIBPATH_list, ';')

    # Add each element of LIBPATH to our DL_LOAD_PATH (necessary on platforms
    # that don't honor our "already opened" trick)
    #for lp in LIBPATH_list
    #    push!(DL_LOAD_PATH, lp)
    #end
end  # __init__()

